### ISSUE TITLE
如何修改备份路径 

### ISSUE THREAD

**Issue by fan1chun** [pkg6/tp5-databackup#48]
```
        try {
            $res = Backup::backup($data["tables"]);
            foreach ($res as $key => $value) {
                if($value == false){
                    return $this->fail($key.'备份失败！');
                }
            }
            return $this->success('备份完毕！', [], 1, 1);
        } catch (\Exception $exception) {
            return $this->fail($exception->getMessage());
        }
```
这样没有问题，
我想问下如何修改备份呢路径，我这样写不行。Call to undefined method tp5er\\Backup\\facade\\Backup::backup()
还有想问下，如果我直接使用Backup::backup备份，还需要执行Backup::cleanup();吗

```class DbBackupController extends BaseAdminController
{
    // 声明配置数组属性  
    protected $config;  
  
    // 构造函数，用于初始化配置数组  
    public function __construct()  
    {  
        $this->config = [  
            "path" => app()->getRootPath() . "public/backup",
            "default" => "sql",
            "backups" => [
                "sql" => [
                    "type" => 'sql',
                ]
            ],
            //一次请求存储100条数据
            "limit"   => 100,
            //生成sql语句的class（目前支持mysql,如需其他可以参考自行修改）
            "build"   => \tp5er\Backup\build\Mysql::class,
        ];  
    }  
    // 备份整个数据库
    public function exportAll()
    {
        $validate = new ExportValidate();
        $data = request()->post();
        if (!$validate->scene("step1")->check($data)) {
            return $this->fail($validate->getError());
        }
        try {
            $db1= new Backup($this->config);
            //执行备份$db1 中的backup
            $res = $db1->backup($data["tables"]);
            foreach ($res as $key => $value) {
                if($value == false){
                    return $this->fail($key.'备份失败！');
                }
            }
            return $this->success('备份完毕！', [], 1, 1);
        } catch (\Exception $exception) {
            return $this->fail($exception->getMessage());
        }
    }
```

还有个问题，如果按ApiController事例里面的Backup::backupStep1 然后执行Backup::backupStep2 
发送备份数据请求：/index/export发送get请求/index/export?index=0&page=0,直到page=0表示该数据备份完成
这里里面的index 和page 分别代表什么，我前端把所有表循环，每次index+1好像不对

**Comment by zzqqw** [comment]
1. 修改配置，修改/you path /config/backup.php
2. Backup::backup 如果你通过接口直接使用这个方法，会出现接口超时的问题，数据量大的时候就会有问题，接口最好通过分步请求
3. 在第一步骤的时候时候 表数据将存储在缓存中 存储的格式 ["table1","table2"],在第二步index 标识从存储中取出的表名实现同步，page表示：如果index = 0 ，page=1 表示 table1表数据还没有备份完，需要继续get请求接口 传入index=0 page=1 直到page=0点情况，table1 表的数据才算备份完毕，你才能继续请求index=1，page=1 依次类推

**Comment by zzqqw** [comment]
#49 提供参考案例

**Comment by fan1chun** [comment]
我有一个表2502条记录，我 "limit"   => 1000, , 因为我前端有一个进度计算。
我现在是 计算3次请求。但实际是会请求4次
![image](https://github.com/pkg6/tp5-databackup/assets/44463181/1aaf10da-246e-4b16-a3f5-28a22927f9be)
![image](https://github.com/pkg6/tp5-databackup/assets/44463181/325dac96-b7d2-4a61-8992-49704e8a1cd4)

能不能在Step1 中返回一下总共需要的步数，还有等下要生成的文件名。

还有就是如果中途备份失败，我想删除当时生成的文件，不知道从哪里获取返回文件名

**Comment by zzqqw** [comment]
Backup::getCurrentBackupFile() 生成的文件名

为什么多请求一次呢
是为了防止余下的数据没有在分页范围内，多出来几条做的填充，内部代码已经处理过，如果没有数据才会将page返回0，表示数据备份完毕

步数计算：
你可以自己计算一下需要多少步 计算方式 ：ceil(总条数/\app()->config->get("backup.limit", 100));

**Comment by zzqqw** [comment]
已经发布到2.1.2版本 代码和 main分支 develop分支是一致的

如果你想把步数计算放进去或者其他修改地方，你可以自己fork一份代码，然后添加方法

~~~
composer require tp5er/tp5-databackup dev-develop
rm -rf vendor/tp5er/tp5-databackup
git clone 您fork仓库地址  vendor/tp5er/tp5-databackup
//TODO
进入vendor/tp5er/tp5-databackup 目录下可以改自己的需求
~~~

**Comment by fan1chun** [comment]
还有个地方不知道是哪里问题Backup::tables();里面 rows 数量好像不对，他这里得到的是0，实际是这个表是有1条数据的
![image](https://github.com/pkg6/tp5-databackup/assets/44463181/b0c54c66-21ce-4e7f-9663-7324de46a6f0)
![image](https://github.com/pkg6/tp5-databackup/assets/44463181/cf2b7dec-f973-45cd-a67c-8edaea7bee85)

**Comment by zzqqw** [comment]
是执行sql`SHOW TABLE STATUS`直接将结果返回，你最好不要使用这个参数，这个参数很不准，至于为什么呢你可以查一下这个sql的用法以及为什么row不准，自己最好count 一下，我就是担心 我在底层中count 会影响mysql性能，所以才没有做count 处理。

**Comment by fan1chun** [comment]
非常感谢，明白了

**Comment by zzqqw** [comment]
我看到你用到Backup 这个类 建议最好不要使用 这个类虽然没有任何问题，但是和2.x版本的备份是不兼容的，如果你要用这个 还不如下载1.x版本的，该类现在标记的是废弃，估计2.2.x版本直接移除，将全力维护2.x版本

**Comment by fan1chun** [comment]
我现在是参考vendor\tp5er\tp5-databackup\src\controller\ApiController.php  写的，没错吧

```
use tp5er\Backup\exception\LockException;
use tp5er\Backup\facade\Backup;
use tp5er\Backup\OPT;
use tp5er\Backup\validate\ExportValidate;
class DbBackupController extends BaseAdminController
{    
// 备份数据库
    public function exportStep2()
    {
        $validate = new ExportValidate();
        $data = request()->get();
        if (!$validate->scene("step2")->check($data)) {
            return $this->fail($validate->getError());
        }
        $index = (int) $data["index"];
        $lastPage = Backup::backupStep2($index, $data["page"]);
        if ($lastPage == 0) {
            return $this->success('备份完毕！', ['index' => $index + 1, 'page' => $lastPage], 1, 1);
        } else {
            $msg = "需要继续进行备份数据！'";
            if ($lastPage < 0) {
                $msg = OPT::backupPage($lastPage);
            }
            return $this->success($msg, ['index' => $index, 'page' => $lastPage], 1, 1);
        }
    }


```

**Comment by zzqqw** [comment]
是的，最新的代码都有参考案例，都是完成测试过的，至于你说的要计算步数，需要你在自己来实现
